Update kotlin to v1.6.0 (#137)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[org.jetbrains.kotlinx:kotlinx-serialization-protobuf](https://togithub.com/Kotlin/kotlinx.serialization)
| `1.5.1` -> `1.6.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlinx:kotlinx-serialization-protobuf/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlinx:kotlinx-serialization-protobuf/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlinx:kotlinx-serialization-protobuf/1.5.1/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlinx:kotlinx-serialization-protobuf/1.5.1/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[org.jetbrains.kotlinx:kotlinx-serialization-json](https://togithub.com/Kotlin/kotlinx.serialization)
| `1.5.1` -> `1.6.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.5.1/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlinx:kotlinx-serialization-json/1.5.1/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[org.jetbrains.kotlinx:kotlinx-serialization-core](https://togithub.com/Kotlin/kotlinx.serialization)
| `1.5.1` -> `1.6.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.5.1/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlinx:kotlinx-serialization-core/1.5.1/1.6.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>Kotlin/kotlinx.serialization
(org.jetbrains.kotlinx:kotlinx-serialization-protobuf)</summary>

###
[`v1.6.0`](https://togithub.com/Kotlin/kotlinx.serialization/blob/HEAD/CHANGELOG.md#160-RC--2023-08-03)

\==================

This release is based on the Kotlin 1.9.0.

##### Removal of Legacy JS target

Some time ago, in Kotlin 1.8, [JS IR compiler was promoted to stable and
old JS compiler was
deprecated](https://kotlinlang.org/docs/whatsnew18.html#stable-js-ir-compiler-backend).
Kotlin 1.9 promotes the usage of deprecated JS compiler to an error. As
a result, kotlinx.serialization no longer builds with the legacy
compiler
and does not distribute artifacts for it. You can read the migration
guide for JS IR compiler
[here](https://kotlinlang.org/docs/js-ir-migration.html).

Also pay attention to the fact that Kotlin/Native also has some
[deprecated
targets](https://kotlinlang.org/docs/native-target-support.html#deprecated-targets)
that are going to be removed in the Kotlin 1.9.20. Therefore,
kotlinx.serialization 1.6.0-RC and 1.6.0 are likely the last releases
that support these targets.

##### Case insensitivity for enums in Json

This release features a new configuration flag for Json:
`decodeEnumsCaseInsensitive`
that allows you to decode enum values in a case-insensitive manner.
For example, when decoding `enum class Foo { VALUE_A , VALUE_B}` both
inputs `"value_a"` and `"value_A"` will yield `Foo.VALUE_A`.
You can read more about this feature in the documentation and
corresponding
[PR](https://togithub.com/Kotlin/kotlinx.serialization/pull/2345).

##### Other bugfixes and enhancements

- Add support to decode numeric literals containing an exponent
([#&#8203;2227](https://togithub.com/Kotlin/kotlinx.serialization/issues/2227))
(thanks to [Roberto Blázquez](https://togithub.com/xBaank))
- Fix NoSuchMethodError related to Java 8 API compatibility
([#&#8203;2328](https://togithub.com/Kotlin/kotlinx.serialization/issues/2328),
[#&#8203;2350](https://togithub.com/Kotlin/kotlinx.serialization/issues/2350))
(thanks to [Björn Kautler](https://togithub.com/Vampire))
- Changed actual FormatLanguage annotation for JS and Native to avoid
problems with duplicating org.intellij.lang.annotations.Language
([#&#8203;2390](https://togithub.com/Kotlin/kotlinx.serialization/issues/2390),
[#&#8203;2379](https://togithub.com/Kotlin/kotlinx.serialization/issues/2379))
- Fix error triggered by 'consume leading class discriminator'
polymorphic parsing optimization
([#&#8203;2362](https://togithub.com/Kotlin/kotlinx.serialization/issues/2362))
- Fix runtime error with Serializer for Nothing on the JS target
([#&#8203;2330](https://togithub.com/Kotlin/kotlinx.serialization/issues/2330))
(thanks to [Shreck Ye](https://togithub.com/ShreckYe))
- Fix beginStructure in JsonTreeDecoder when inner structure descriptor
is same as outer
([#&#8203;2346](https://togithub.com/Kotlin/kotlinx.serialization/issues/2346))
(thanks to [Ugljesa Jovanovic](https://togithub.com/ionspin))
- Actualize 'serializer not found' platform-specific message
([#&#8203;2339](https://togithub.com/Kotlin/kotlinx.serialization/issues/2339))
- Fixed regression with serialization using a list parametrized with
contextual types
([#&#8203;2331](https://togithub.com/Kotlin/kotlinx.serialization/issues/2331))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/julioromano/mooviez).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNi41Ni4wIiwidXBkYXRlZEluVmVyIjoiMzYuNTYuMCIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>